### ISSUE TITLE
Reliable wrong ip range

### ISSUE THREAD

**Issue by Exoshare** [Maikuolan/zbb-badip-fork#1]
Thanks for the updates :) 46.165.64.0/16 i think it has to be changed to 46.165.64.0/18 ?

**Comment by Maikuolan** [comment]
No problem. :-)

I don't see `46.165.64.0/16` or `46.165.64.0/18` anywhere in the current signatures, but we have `46.165.0.0/16` in the current signatures. Is that the range you meant?

`$ax += cidrblock($address,'46.165.0.0/16','Reliable Hosting Services. Not an access provider ISP (ASN-RELIA-07). ');`

Interestingly, I checked the current ranges for the two associated ASNs (29713, 33597) just now (using *bgp.he.net*), and they seem to have far fewer ranges currently than they did only 5 days ago. Maybe they've recently sold off some ranges to other providers?

I think `46.165.0.0/16` can probably be safely removed from the signatures; It seems to now belong to AS49218, a different provider. I'll need to look carefully at some of the others, to determine whether these removed or sold ranges should still be blocked or whether they can be safely removed.

I'll update shortly tonight. Thanks for spotting. :+1:

**Comment by Exoshare** [comment]
Hello, Thanks for your fast reply :) the problem here that i got real users from these ips:
 this one belongs to SFR France: 46.165.64.0/18
http://bgp.he.net/net/46.165.64.0/18
//$ax += cidrblock($address,'46.165.0.0/16','Reliable Hosting Services. Not an access provider ISP (ASN-RELIA-07). ');
$ax += cidrblock($address,'46.165.192.0/18','Leaseweb Network (ASN-LEASEWEB-016). ');
These are duplicates.
I think this block is REALLY shared  :)

**Comment by Maikuolan** [comment]
Oh wow.. I think you're right. o.0

It's annoying when ASNs share CIDRs like that; Becomes more difficult to determine who truly owns the shared ranges.

It's taking me a little longer than expected to check through the remaining CIDRs in those sections (which seem to now need updating again, due to changes in their announced ranges), due to being caught up with other work at home. I should have those sections updated again within a day or so, but, in the meanwhile, I've synced a new commit with the two problematic ranges commented out; This new commit should resolve the immediate problem, at least. :-)

**Comment by Maikuolan** [comment]
Okay, all sorted.

When you get the chance to test the latest commit, could you let me know whether problems persist? If everything seems to be okay now, I can close this issue. Cheers. :-)

**Comment by Exoshare** [comment]
You have removed the /16 even when it contains leaseweb range.
This is how exactly that range is divided:
46.165.0.0/18 Nizhnetagilskie Kompyuternye Seti LLC RU (I'm blocking whole RU Country)
46.165.64.0/18 SFR France xDSL (Human beings) 
46.165.128.0/18 inexio Informationstechnologie und Telekommunikation KGaA DE (Deutsch internet provider but also offering cloud hosting on that ip range)
46.165.192.0/18 Leaseweb Deutschland GmbH DE (Leaseweb!)
Sorry for that but you should update again :)

**Comment by Maikuolan** [comment]
It's okay, nothing to be sorry about; We want to get it right. I appreciate the input. :-)

I'll update again in a few minutes.

**Comment by Maikuolan** [comment]
There we go; The Leaseweb range has been put back in again now. :-)

The other two groups ("Nizhnetagilskie Kompyuternye", AS49218, and "inexio Informationstechnologie und Telekommunikation", AS42652) seem to have very low HE ranks at the moment (according to `sitevet.com`). I'll ask some of the other users how they feel about these ASNs, to see whether they think we should block them, too, but, I'll avoid adding sections for them for at least the time being (I haven't yet personally seen anything nasty coming from these ASNs, but, there are a few odd spam event records for them, and if they offer cloud services, like any others offering cloud services, there's always the potential for future problems, of course).

**Comment by Maikuolan** [comment]
@Exoshare How's is looking at the moment? No more false positives?

**Comment by Exoshare** [comment]
Everything is working fine. Thanks for the update ! :+1:

**Comment by Maikuolan** [comment]
No worries, and happy to hear! :-)

Will close now.
