### ISSUE TITLE
Common Prefix @ Signatures

### ISSUE THREAD

**Issue by dev-101** [Maikuolan/zbb-badip-fork#8]
Hi,
I was thinking about an idea to add a common prefix to certain signatures, that can be useful later for custom rules/mods and even log reading. Because, some services may and usually do contain that keyword, but other not.

Examples:
1. if it is a cloud, than add [CLOUD] (or simply "CLOUD") to the rule's why section
2. [HOSTING]
3. [DIRTY30] (for other file)
4. [SPAM] (for spammy networks)

It is not urgent, it could be implemented gradually, first for the most known and largest blocks.

What do you think?
Thanks

**Comment by Maikuolan** [comment]
Definitely, this is a good idea, and could be very helpful. :-)

I think doing it gradually probably would make the most sense, maybe over time, as sections are updated; This should hopefully minimise the amount of work required by others in regards to custom bypasses and such.

I'll start adding these in whenever I update sections.

**Comment by dev-101** [comment]
No worries and no hurry, gradually and by priority (the largest/most popular first).

Now, maybe the idea could be streamlined, there is a little difference between hosting and cloud (as former are usually part of larger cloud networks), also dirty30 could be replaced either by cloud or spam prefixes (depends).

Thanks
